### PR TITLE
Remove contributors from package description

### PR DESCRIPTION
**Pull request by mjftw**

### CODE REVIEW

**Comment by Pixep** [comment]
@mjftw So do you still want to remove it? Seemed like you had doubts last time :)

**Comment by mjftw** [comment]
> @mjftw So do you still want to remove it? Seemed like you had doubts last time :)

I think it's probably a good idea. That information is probably better suited to the README.

**Review by Pixep — APPROVED** [review]
Looks good!

**Comment by Pixep** [comment]
Looking good, merging.

**Pull request merged**
