### PR TITLE
Closes #75, closes #90 Feature/testuite doesnt need all tests in init

### LINKED ISSUE #75: Pluma --plugins flag behaves unexpectedly
**Describe the bug**
The Pluma `--plugin` flag is not working as intended, and gives some rubbish error messages.

The plugins directory specified should have the following structure:
`<plugindir>/module_name/<filename>.py`
and `<filename>.py` should contain the tests.

The error given when the plugins directory has the following structure is awful:
`<plugindir>/<filename>.py`
and `<filename>.py` should contain the tests.

(Probably this structure should be allowed anyway)
```
(venv) merlin@pangolin:~/projects/pluma-automation$ pluma -c ./pluma.yml -t ./pluma-target.yml --plugin ./plugindir/ --debug check
No console defined in the device configuration file
Components:
    Serial:  None
    SSH:  None
    Prompt:  \S+@\S+:
    Login:  mendel
    Password:  ******
    Power control:  None
    Storage:  None
    USB Hub:  None

Traceback (most recent call last):
  File "/home/merlin/projects/pluma-automation/pluma/__main__.py", line 87, in main
    check_only=True)
  File "/home/merlin/projects/pluma-automation/pluma/cli/api.py", line 26, in execute_run
    target_config_path, show_tests_list=check_only)
  File "/home/merlin/projects/pluma-automation/pluma/cli/api.py", line 79, in build_test_controller
    testsConfig = TestsConfig(tests_config, Pluma.tests_providers())
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 34, in __init__
    self.__populate_tests(config)
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 85, in __populate_tests
    self.tests = self.tests_from_sequence(sequence, self.test_providers)
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 140, in tests_from_sequence
    supported_actions=supported_actions)
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 156, in tests_from_action
    tests = provider.all_tests(key=action_key, config=Configuration(action_config))
  File "/home/merlin/projects/pluma-automation/pluma/cli/pythontestsprovider.py", line 31, in all_tests
    all_tests = self.find_python_tests()
  File "/home/merlin/projects/pluma-automation/pluma/cli/pythontestsprovider.py", line 64, in find_python_tests
    name=f'{cls.__module__[cls.__module__.index(module_name):]}.{class_name}',
ValueError: substring not found
substring not found
```

If the plugin dir structure does look correct, we get a different error in the `pluma.yaml`.

Plugin dir structure: `plugindir/testmodule/filesystem.py`

pluma.yml
```yaml
settings:
  continue_on_fail: true
  iterations: 1

sequence:
- core_tests:
    include: [testmodule.filesystem]
    exclude: []
    parameters:
      testmodule.filesystem.FileExists:
        path: '/bin/bash'
        run_on_host: true

```

```
(venv) merlin@pangolin:~/projects/pluma-automation$ pluma -c ./pluma.yml -t ./pluma-target.yml --plugin ./plugindir/ --debug check
No console defined in the device configuration file
Components:
    Serial:  None
    SSH:  None
    Prompt:  \S+@\S+:
    Login:  mendel
    Password:  ******
    Power control:  None
    Storage:  None
    USB Hub:  None

Traceback (most recent call last):
  File "/home/merlin/projects/pluma-automation/pluma/__main__.py", line 87, in main
    check_only=True)
  File "/home/merlin/projects/pluma-automation/pluma/cli/api.py", line 26, in execute_run
    target_config_path, show_tests_list=check_only)
  File "/home/merlin/projects/pluma-automation/pluma/cli/api.py", line 79, in build_test_controller
    testsConfig = TestsConfig(tests_config, Pluma.tests_providers())
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 34, in __init__
    self.__populate_tests(config)
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 85, in __populate_tests
    self.tests = self.tests_from_sequence(sequence, self.test_providers)
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 140, in tests_from_sequence
    supported_actions=supported_actions)
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 156, in tests_from_action
    tests = provider.all_tests(key=action_key, config=Configuration(action_config))
  File "/home/merlin/projects/pluma-automation/pluma/cli/pythontestsprovider.py", line 34, in all_tests
    includes+excludes)
  File "/home/merlin/projects/pluma-automation/pluma/cli/pythontestsprovider.py", line 100, in validate_match_strings
    raise ValueError(f'Some include/exclude rules matched no tests: {not_matched}')
ValueError: Some include/exclude rules matched no tests: ['testmodule.filesystem']
Some include/exclude rules matched no tests: ['testmodule.filesystem']
(venv) merlin@pangolin:~/projects/pluma-automation$
```

Looks like the plugin dir is not being found?

### LINKED ISSUE #90: Make it so `__init__.py` doesn't need to include every test class
> Fixed, I pushed a quick commit. Feel free to squash. This is basically normal, no test was found, because the `__init__.py` was not including your class

Ah okay makes sense.
I think if we could find a way where this doesn't need to be done for every new test added then that would be good.
I can see this tripping people up a lot in future when adding new tests, and it means the `__init__.py` will have to be modified a lot,  potentially causing a lot of merge conflicts as people add more tests.

_Originally posted by @mjftw in https://github.com/Witekio/pluma-automation/pull/79#issuecomment-698850474_

### PR DESCRIPTION
**Pull request by mjftw**
With this we can now find tests in scripts either in the root `--plugin` dir (and in `pluma.plugins`) or in submodules.
For tests in submodules, you now only need to import the submodule in the module `__init__` init, not every test within that submodule. Tests in submodules are found automatically.

This PR also fixes an existing bug I found where `TestBase` based classes imported into the `mytests.py` test module were also found and assumed to be real runnable tests.
E.g.
mytests.py
```python
from pluma.test import ShellTest
```

Previously `ShellTest` this would have been reported as being one of the tests in the `mytests` module, so could have been called in the yaml with
```yaml
sequence:
- core_tests:
    include: [mytests]
    parameters:
      mytests.ShellTest:
        name: Merlin
      topleveltests.World:
```

This bug is also what was causing the error `ValueError: substring not found` seen in https://github.com/Witekio/pluma-automation/issues/75. This PR effectively closes that issue as well.

### CODE REVIEW

**Comment by Pixep** [comment]
Quick question: In our networking tests, we have `NetworkingTestBase`. Is this one exposed automatically now? Because it shouldn't, as this is a base test only. Any idea to exclude it, if so?

**Comment by mjftw** [comment]
> Quick question: In our networking tests, we have `NetworkingTestBase`. Is this one exposed automatically now? Because it shouldn't, as this is a base test only. Any idea to exclude it, if so?

I'd say yes it'll be exposed, hadn't considered base classes. Hmmmm
1. Well one way around this would be to rely on naming convention. E.g. if the class name ends with "Base" it's not imported.
I'm a massive fan of relying on naming convention though.
2. A different way would be to check if the class is subclassed, and not include it if it is, but this has the disadvantage of silently breaking inclusion for base classes that people intend to make instances of.
3. We could add an optional `__all__` array (or some other name) to the file denoting all of the classes that should be found, but adds complexity. 
4. We could leave some marker on the individual base classes in whatever form (be it attributes, functions, inheritance etc etc), but that then requires the test class be modified, which I don't like.
5. We could go a similar route that we have with DeviceActions with registering them and remove the custom code to check for TestBase type classes. If we were to abstract the registration code then this could be a nice scalable solution for other user expanded things going forward.

So options I can think of are rely in naming convention or only include classes that are leaf classes.

**Comment by mjftw** [comment]
> > Quick question: In our networking tests, we have `NetworkingTestBase`. Is this one exposed automatically now? Because it shouldn't, as this is a base test only. Any idea to exclude it, if so?
> 
> I'd say yes it'll be exposed, hadn't considered base classes. Hmmmm
> 
>     1. Well one way around this would be to rely on naming convention. E.g. if the class name ends with "Base" it's not imported.
>        I'm a massive fan of relying on naming convention though.
> 
>     2. A different way would be to check if the class is subclassed, and not include it if it is, but this has the disadvantage of silently breaking inclusion for base classes that people intend to make instances of.
> 
>     3. We could add an optional `__all__` array (or some other name) to the file denoting all of the classes that should be found, but adds complexity.
> 
>     4. We could leave some marker on the individual base classes in whatever form (be it attributes, functions, inheritance etc etc), but that then requires the test class be modified, which I don't like.
> 
>     5. We could go a similar route that we have with DeviceActions with registering them and remove the custom code to check for TestBase type classes. If we were to abstract the registration code then this could be a nice scalable solution for other user expanded things going forward.
> 
> 
> Thoughts?

Either way, this fixes an existing bug, so if we don't want to merge this right away we should probably still keep the fix. Maybe via a new PR.

**Comment by Pixep** [comment]
> We could go a similar route that we have with DeviceActions with registering them and remove the custom code to check for TestBase type classes. If we were to abstract the registration code then this could be a nice scalable solution for other user expanded things going forward.

Yeah, that's probably what I would lean towards. We can already integrate that, once rebased. Currently it includes commits already on master (but yet different), so you'll have to `rebase --onto` :)

**Comment by mjftw** [comment]
> > We could go a similar route that we have with DeviceActions with registering them and remove the custom code to check for TestBase type classes. If we were to abstract the registration code then this could be a nice scalable solution for other user expanded things going forward.
> 
> Yeah, that's probably what I would lean towards. We can already integrate that, once rebased. Currently it includes commits already on master (but yet different), so you'll have to `rebase --onto` :)

Okay, I'll go with that.

One thing to note is that even without these changes, a user could still add a python file in the root of their `--plugin` dir, and if it contained any `TestBase` based classes they would be imported.

I think for the `--plugin` dir, being able to put the test scripts in the root of the dir makes a lot more sense than having to nest them inside another dir. Does mean that the issue you mentioned is still here though.

**Comment by mjftw** [comment]
I've done a pretty manual rebase onto master with this branch (using cherry-picks and and hard resets), edited the branch history to split up a commit into stuff that adds bugfix and stuff that adds new features, and finally I've created a new branch and PR from just the bugfix bits.

**Review by Pixep — APPROVED** [review]
Thanks, good one

**Pull request merged**
