### PR TITLE
Add CLI --plugin tests in cli unit test folder

### PR DESCRIPTION
**Pull request by mjftw**
This PR adds tests which show the failure behaviour mentioned in https://github.com/Witekio/pluma-automation/issues/75.

It is a WIP and further commits will fix the issue, rather than just highlight it.

### CODE REVIEW

**Comment by mjftw** [comment]
@Pixep , can you see anything wrong with the config files or test I've created that would cause the following error?
```
Pluma CLI exited with code -1 
stdout: No console defined in the device configuration file
Some include/exclude rules matched no tests: ['example_plugin.mytests']
```

**Comment by Pixep** [comment]
Thanks for the unit test @mjftw. Can you move it under `tests/generic/cli`? There's now `pluma.py` there, and this would probably make more sense to be in this file, or at least under `cli`.

> @Pixep , can you see anything wrong with the config files or test I've created that would cause the following error?

Sure I can have a look

**Comment by mjftw** [comment]
> Thanks for the unit test @mjftw. Can you move it under `tests/generic/cli`? There's now `pluma.py` there, and this would probably make more sense to be in this file, or at least under `cli`.
> 
> > @Pixep , can you see anything wrong with the config files or test I've created that would cause the following error?
> 
> Sure I can have a look

Sure, good thinking.
Done.

**Comment by Pixep** [comment]
Fixed, I pushed a quick commit. Feel free to squash. This is basically normal, no test was found, because the __init__.py was not including your class

**Comment by mjftw** [comment]
> Fixed, I pushed a quick commit. Feel free to squash. This is basically normal, no test was found, because the `__init__.py` was not including your class

Ah nice one 👍🏼

**Comment by mjftw** [comment]
> Fixed, I pushed a quick commit. Feel free to squash. This is basically normal, no test was found, because the `__init__.py` was not including your class

Ah okay makes sense.
I think if we could find a way where this doesn't need to be done for every new test added then that would be good.
I can see this tripping people up a lot in future when adding new tests, and it means the `__init__.py` will have to be modified a lot,  potentially causing a lot of merge conflicts as people add more tests.

**Pull request merged**
