### PR TITLE
Check CLI arg config files exist

### PR DESCRIPTION
**Pull request by mjftw**
I found the error message where the CLI can't find the config file may not immediately point to how to solve it, and would be better handled by argparse.

Before:
```
(venv) merlin@pangolin:~/projects/pluma-automation$ pluma -c foo -t bar
Target config "bar" does not exist

(venv) merlin@pangolin:~/projects/pluma-automation$ pluma -t bar -c foo
Target config "bar" does not exist
```

Now:
```
(venv) merlin@pangolin:~/projects/pluma-automation$ pluma -t bar -c foo
usage: pluma [-h] [-v] [-q] [-c CONFIG] [-t TARGET] [--plugin PLUGIN] [-f]
             [--silent] [--debug]
             [{run,check,tests,clean,version}]
pluma: error: argument -t/--target: Target config file does not exist: bar

(venv) merlin@pangolin:~/projects/pluma-automation$ pluma -c foo -t bar
usage: pluma [-h] [-v] [-q] [-c CONFIG] [-t TARGET] [--plugin PLUGIN] [-f]
             [--silent] [--debug]
             [{run,check,tests,clean,version}]
pluma: error: argument -c/--config: Config file does not exist: foo
```

Added an extra commit to check the plugins dir at the same time.
```
(venv) merlin@pangolin:~/projects/pluma-automation$ pluma --plugin floop -t bar -c foo
usage: pluma [-h] [-v] [-q] [-c CONFIG] [-t TARGET] [--plugin PLUGIN] [-f]
             [--silent] [--debug]
             [{run,check,tests,clean,version}]
pluma: error: argument --plugin: Plugins directory does not exist: floop
```

### CODE REVIEW

**Comment by Pixep** [comment]
Oh that's neat, like it. Unit tests failing, but that's a good contrib

**Review by Pixep — APPROVED** [review]
Approving ahead of unit tests fixes

**Comment by mjftw** [comment]
Found and fixed the bug that was causing CI failures, ready for re-review.

**Review by Pixep — APPROVED** [review]
Good to go :sunglasses:

**Pull request merged**
